application:
  port: 8000

mongo:
 username: ""
 password: ""
 uri: "mongodb://10.20.30.20:27017"
 host: "10.20.30.20"
 port: 27017
 db: "template_db"
 collection: "template"
 require_auth: false
 pool_size: 1
 connection_timeout: 1
 

redis:
  url: "redis://10.20.30.5:6379"
  pool_size: 1
  pool_max_open: 16
  pool_max_idle: 8
  pool_timeout_seconds: 1
  pool_expire_seconds: 60

sqlite:
  path: "senzor.db"
  schema: "static/schema.sql"
  pool_size: 1
  connection_timeout: 1

postgres:
  username: "djhunter67"
  password: "PNF27156"
  port: 5432
  host: "10.20.30.23"
  db: "test"
  require_auth: true
  schema: "static/schema.sql"
  app_name: "web_template"
  connection_timeout: 1
  working_memory: "256MB"

